# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            London Genetics Network
tagline:          'A Jekyll theme'
description:      'A network for human genetics researchers who work in London and the surrounding areas. Follow us on <a href="https://twitter.com/LdnGeneNet" target="_blank">Twitter</a> for updates of meetings, workshops and career opportunities.'
# baseurl:          "/London_Genetic_Network"
# url: "https://kai-lim.github.io"

paginate:         5

# Custom vars
version:          2.1.0



plugins: [jekyll-paginate]

